

apiRules:
# Exclude System.Object or System.Reflection to avoid having .Equals and stuff in the docs
- exclude:
    uidRegex: ^System\.

# hides things like Microsoft.Extensions.DependencyInjection etc.
- exclude:
    uidRegex: ^Microsoft\.


# Exclude any tests
- exclude:
    uidRegex: ^Oqtane.Test\.
- exclude:
    uidRegex: ^Oqtane.Oqtane.Client.Tests\.

# exclude Database (mostly MySql etc. connectors) and Migrations (upgrade-scenarios) Namespaces from the docs
- exclude:
    uidRegex: ^Oqtane.Database\.
- exclude:
    uidRegex: ^Oqtane.Databases\.
- exclude:
    uidRegex: ^Oqtane.Maui    
- exclude:
    uidRegex: ^Oqtane.Migrations\.
- exclude:
    uidRegex: ^Oqtane.Modules.Admin\.
- exclude:
    uidRegex: ^Oqtane._Imports
- exclude:
    uidRegex: ^Oqtane.Installer    
- exclude:
    uidRegex: ^Oqtane.Modules.HtmlText
- exclude:
    uidRegex: ^Oqtane.Repository.Databases.Interfaces
- exclude:
    uidRegex: ^Oqtane.Themes.BlazorTheme
- exclude:
    uidRegex: ^Oqtane.Themes.OqtaneTheme

# Exclude classes which are just Blazor imports
- exclude:
    uidRegex: \._Imports$

# exclude a strange namespace which should probably not be there
- exclude:
    uidRegex: ^OqtaneSSR.Extensions
    
# Exclude anything marked as PrivateApi
# In future, we may change this to only show things which are PublicApi (recommendation of iJungleboy)
- exclude:
    hasAttribute:
      uid: Oqtane.Documentation.PrivateApi

      # Oqtane.Modules.Admin
      #HtmlModule
      #MAUI
  